#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to Perform a 301-redirection

# Upadate Packages before Installations
sudo apt-get update
sudo apt-get install -y nginx

# Create index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Perform  301 Redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/besthor permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx service
sudo service nginx restart
