#!/usr/bin/env bash
# Create script that install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to both web-01 and web-02 servers
# Distribute the requests using  roundrobin algorithm

# Install and configure HAproxy on lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  Eliud254_frontend
        bind *:80
        mode http
        default_backend Eliud254_backend
backend Eliud254_backend
        balance roundrobin
        server 11480-web-01 52.91.121.86:80 check
        server 11480-web-02 54.227.224.9:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
