#!/usr/bin/env bash
# Bash script that displays:
# To infinity and beyond indefinitely
# I am invincible!!! when receiving a SIGTERM signal
while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM 
done
