#!/usr/bin/env bash
#displays numbers 1 to 20 ;
#Display bad luck from china on the 4rth iteration
#Display bad luck from japan on the 9th iteration
#Display bad luck from italy for the 17th iteration

count=1

while [ $count -le 10 ]
do
    echo "$count"
    case $count in
	"4") echo " bad luck from China";;
	"9") echo "bad luck from Japan";;
	"17") echo "bad luck from Italy";;
    esac
    (( count++ ))

done
