#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements
grep -Evw "(localhost|facebook)" /etc/hosts > ~/hosts.new
echo "127.0.0.2 localhost" >> ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
